JOINING:
a) Concat - Quickest way (row/column-wise) - Stacking , Duplication

b) Merge - database style joins (sql joiner) ~ Powerful.

c) Join - shorthand for merge (index)

## MERGE

In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    'Stud_ID':[1,2,3,4],
    'Name':['Alice','Bob','Jane','Moses'],
    'Subject':['Math','Eng','Hist','Sci']
})

In [7]:
df2 = pd.DataFrame({
    'Stud_ID':[3,4,5,6],
    'Score':['90','85','88','92'],
    'Grade':['A','B','B+','A-']
})

In [4]:
df1

   Stud_ID   Name Subject
0        1  Alice    Math
1        2    Bob     Eng
2        3   Jane    Hist
3        4  Moses     Sci

In [5]:
df2

   ID Score Grade
0   3    90     A
1   4    85     B
2   5    88    B+
3   6    92    A-

DEFAULT WAY

In [8]:
pd.merge(left=df1,right=df2)

   Stud_ID   Name Subject Score Grade
0        3   Jane    Hist    90     A
1        4  Moses     Sci    85     B

TYPES OF JOIN/MERGE:

In [10]:
pd.merge(df1,df2,on='Stud_ID',how='inner')

   Stud_ID   Name Subject Score Grade
0        3   Jane    Hist    90     A
1        4  Moses     Sci    85     B

In [15]:
df1.merge(df2,on='Stud_ID',how='inner')

   Stud_ID   Name Subject Score Grade
0        3   Jane    Hist    90     A
1        4  Moses     Sci    85     B

In [11]:
pd.merge(df1,df2,on='Stud_ID',how='left')

   Stud_ID   Name Subject Score Grade
0        1  Alice    Math   NaN   NaN
1        2    Bob     Eng   NaN   NaN
2        3   Jane    Hist    90     A
3        4  Moses     Sci    85     B

In [12]:
pd.merge(df1,df2,on='Stud_ID',how='right')

   Stud_ID   Name Subject Score Grade
0        3   Jane    Hist    90     A
1        4  Moses     Sci    85     B
2        5    NaN     NaN    88    B+
3        6    NaN     NaN    92    A-

In [13]:
pd.merge(df1,df2,on='Stud_ID',how='outer')

   Stud_ID   Name Subject Score Grade
0        1  Alice    Math   NaN   NaN
1        2    Bob     Eng   NaN   NaN
2        3   Jane    Hist    90     A
3        4  Moses     Sci    85     B
4        5    NaN     NaN    88    B+
5        6    NaN     NaN    92    A-

LEFT ON & RIGHT ON

In [18]:
df1 = pd.DataFrame({
    'Stud_ID':[1,2,3,4],
    'Name':['Alice','Bob','Jane','Moses'],
    'Subject':['Math','Eng','Hist','Sci']
})

df2 = pd.DataFrame({
    'ID':[3,4,5,6],
    'Score':['90','85','88','92'],
    'Grade':['A','B','B+','A-']
})

In [19]:
pd.merge(df1,df2,left_on='Stud_ID',right_on='ID',how='inner')

   Stud_ID   Name Subject  ID Score Grade
0        3   Jane    Hist   3    90     A
1        4  Moses     Sci   4    85     B

LEFT INDEX & RIGHT INDEX

In [20]:
pd.merge(df1,df2,left_index=True,right_index=True)

   Stud_ID   Name Subject  ID Score Grade
0        1  Alice    Math   3    90     A
1        2    Bob     Eng   4    85     B
2        3   Jane    Hist   5    88    B+
3        4  Moses     Sci   6    92    A-

Concat: (Azadi)

## JOIN

In [32]:
df1 = pd.DataFrame({
    'Stud_ID':[1,2,3,4],
    'Name':['Alice','Bob','Jane','Moses'],
    'Subject':['Math','Eng','Hist','Sci']
})

df2 = pd.DataFrame({
    'ID':[3,4,5,6],
    'Score':['90','85','88','92'],
    'Grade':['A','B','B+','A-']
})

In [33]:
df1.set_index('Stud_ID',inplace=True)

In [24]:
df1

          Name Subject
Stud_ID
1        Alice    Math
2          Bob     Eng
3         Jane    Hist
4        Moses     Sci

In [34]:
df2.set_index('ID',inplace=True)

In [26]:
df2

   Score Grade
ID
3     90     A
4     85     B
5     88    B+
6     92    A-

In [35]:
df1.join(df2,how='inner')           # Alternative to LEFT ON & RIGHT ON (USE SET_INDEX FUNCTION)

    Name Subject Score Grade
3   Jane    Hist    90     A
4  Moses     Sci    85     B