### GROUP BY
(pip install openpyxl)

In [5]:
import pandas as pd

In [6]:
data = pd.read_csv(r'C:\Users\ADMIN\Desktop\ZINDUA\PYDATA\QVI_purchase_behaviour.csv')

In [7]:
df = pd.read_excel(r'C:\Users\ADMIN\Desktop\ZINDUA\PYDATA\QVI_transaction_data.xlsx')

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72637 entries, 0 to 72636
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   LYLTY_CARD_NBR    72637 non-null  int64
 1   LIFESTAGE         72637 non-null  object
 2   PREMIUM_CUSTOMER  72637 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.7+ MB

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264836 entries, 0 to 264835
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DATE            264836 non-null  int64
 1   STORE_NBR       264836 non-null  int64
 2   LYLTY_CARD_NBR  264836 non-null  int64
 3   TXN_ID          264836 non-null  int64
 4   PROD_NBR        264836 non-null  int64
 5   PROD_NAME       264836 non-null  object
 6   PROD_QTY        264836 non-null  int64
 7   TOT_SALES       264836 non-null  float64
dtypes: float64(1), int64(6), object(1)
memory usage: 16.2+ MB

In [9]:
full_df = data.merge(df,how='left',on='LYLTY_CARD_NBR')

In [8]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264836 entries, 0 to 264835
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   LYLTY_CARD_NBR    264836 non-null  int64
 1   LIFESTAGE         264836 non-null  object
 2   PREMIUM_CUSTOMER  264836 non-null  object
 3   DATE              264836 non-null  int64
 4   STORE_NBR         264836 non-null  int64
 5   TXN_ID            264836 non-null  int64
 6   PROD_NBR          264836 non-null  int64
 7   PROD_NAME         264836 non-null  object
 8   PROD_QTY          264836 non-null  int64
 9   TOT_SALES         264836 non-null  float64
dtypes: float64(1), int64(6), object(3)
memory usage: 20.2+ MB

What can we ask from this dat?

Univariate, Bivariate & Multivariate Analysis (Global View - Summary Stats)
1. Univariate:
- How big is our customer base
- How many unique products
- When does my dataset range from?
- How many transaction
- Total quantity sold
- Distribution; How many customers; lifestage, premium customer
- Distribution of sales (); Median sales, outliers
- Distribution of premium customer by lifestage
- Quantity by lifestage & premium customer
- Total sales by lifestage & premium customer

In [9]:
full_df.columns

Index(['LYLTY_CARD_NBR', 'LIFESTAGE', 'PREMIUM_CUSTOMER', 'DATE', 'STORE_NBR',
       'TXN_ID', 'PROD_NBR', 'PROD_NAME', 'PROD_QTY', 'TOT_SALES'],
      dtype='object')

In [6]:
full_df['LIFESTAGE'].unique()

array(['YOUNG SINGLES/COUPLES', 'YOUNG FAMILIES', 'OLDER SINGLES/COUPLES',
       'MIDAGE SINGLES/COUPLES', 'NEW FAMILIES', 'OLDER FAMILIES',
       'RETIREES'], dtype=object)

In [7]:
full_df['LIFESTAGE'].nunique()

7

In [9]:
full_df.groupby('LIFESTAGE')[['TOT_SALES']].sum().sort_values(by='TOT_SALES',ascending=False)

                        TOT_SALES
LIFESTAGE
OLDER SINGLES/COUPLES   402426.75
RETIREES                366470.90
OLDER FAMILIES          353767.20
YOUNG FAMILIES          316160.10
YOUNG SINGLES/COUPLES   260405.30
MIDAGE SINGLES/COUPLES  184751.30
NEW FAMILIES             50433.45

In [15]:
full_df.groupby(['LIFESTAGE','PREMIUM_CUSTOMER'])[['TOT_SALES']].mean()

                                         TOT_SALES
LIFESTAGE              PREMIUM_CUSTOMER
MIDAGE SINGLES/COUPLES Budget             7.074661
                       Mainstream         7.647284
                       Premium            7.112056
NEW FAMILIES           Budget             7.297321
                       Mainstream         7.317806
                       Premium            7.231655
OLDER FAMILIES         Budget             7.269570
                       Mainstream         7.262395
                       Premium            7.322945
OLDER SINGLES/COUPLES  Budget             7.430315
                       Mainstream         7.282116
                       Premium            7.449766
RETIREES               Budget             7.443445
                       Mainstream         7.252262
                       Premium            7.456174
YOUNG FAMILIES         Budget             7.287201
                       Mainstream         7.189025
                       Premium            7.266756
YOUNG SINGLES/COUPLES  Budget             6.615624
                       Mainstream         7.558339
                       Premium            6.629852

In [16]:
full_df.groupby(['LIFESTAGE','PREMIUM_CUSTOMER'])[['TOT_SALES','PROD_QTY']].mean()

                                         TOT_SALES  PROD_QTY
LIFESTAGE              PREMIUM_CUSTOMER
MIDAGE SINGLES/COUPLES Budget             7.074661  1.891633
                       Mainstream         7.647284  1.911656
                       Premium            7.112056  1.889727
NEW FAMILIES           Budget             7.297321  1.853910
                       Mainstream         7.317806  1.857634
                       Premium            7.231655  1.860919
OLDER FAMILIES         Budget             7.269570  1.945812
                       Mainstream         7.262395  1.948610
                       Premium            7.322945  1.980969
OLDER SINGLES/COUPLES  Budget             7.430315  1.913403
                       Mainstream         7.282116  1.910525
                       Premium            7.449766  1.914273
RETIREES               Budget             7.443445  1.892244
                       Mainstream         7.252262  1.887543
                       Premium            7.456174  1.900122
YOUNG FAMILIES         Budget             7.287201  1.940749
                       Mainstream         7.189025  1.940342
                       Premium            7.266756  1.937732
YOUNG SINGLES/COUPLES  Budget             6.615624  1.803830
                       Mainstream         7.558339  1.852498
                       Premium            6.629852  1.804012

In [ ]:
full_df.groupby(['LIFESTAGE']).agg({'TOT_SALES':'sum', 'PROD_QTY':'mean'})      # Key-Value Pair

                        TOT_SALES  PROD_QTY
LIFESTAGE
MIDAGE SINGLES/COUPLES  184751.30  1.900478
NEW FAMILIES             50433.45  1.856771
OLDER FAMILIES          353767.20  1.954729
OLDER SINGLES/COUPLES   402426.75  1.912719
RETIREES                366470.90  1.892289
YOUNG FAMILIES          316160.10  1.939828
YOUNG SINGLES/COUPLES   260405.30  1.831762

In [ ]:
full_df.groupby(['LIFESTAGE']).agg(total_sales = ('TOT_SALES','sum'),av_sales = ('TOT_SALES','mean'))       # As a Tuple.

                        total_sales  av_sales
LIFESTAGE
MIDAGE SINGLES/COUPLES    184751.30  7.357678
NEW FAMILIES               50433.45  7.289124
OLDER FAMILIES            353767.20  7.279760
OLDER SINGLES/COUPLES     402426.75  7.386823
RETIREES                  366470.90  7.364325
YOUNG FAMILIES            316160.10  7.252709
YOUNG SINGLES/COUPLES     260405.30  7.158515

### PIVOT TABLE

In [21]:
pd.pivot_table(full_df,values=['TOT_SALES', 'PROD_QTY'], index='LIFESTAGE', columns='PREMIUM_CUSTOMER',aggfunc='mean')

                        PROD_QTY                      TOT_SALES             \
PREMIUM_CUSTOMER          Budget Mainstream   Premium    Budget Mainstream
LIFESTAGE
MIDAGE SINGLES/COUPLES  1.891633   1.911656  1.889727  7.074661   7.647284
NEW FAMILIES            1.853910   1.857634  1.860919  7.297321   7.317806
OLDER FAMILIES          1.945812   1.948610  1.980969  7.269570   7.262395
OLDER SINGLES/COUPLES   1.913403   1.910525  1.914273  7.430315   7.282116
RETIREES                1.892244   1.887543  1.900122  7.443445   7.252262
YOUNG FAMILIES          1.940749   1.940342  1.937732  7.287201   7.189025
YOUNG SINGLES/COUPLES   1.803830   1.852498  1.804012  6.615624   7.558339


PREMIUM_CUSTOMER         Premium
LIFESTAGE
MIDAGE SINGLES/COUPLES  7.112056
NEW FAMILIES            7.231655
OLDER FAMILIES          7.322945
OLDER SINGLES/COUPLES   7.449766
RETIREES                7.456174
YOUNG FAMILIES          7.266756
YOUNG SINGLES/COUPLES   6.629852

### MISSINGNESS

In [3]:
# data = pd.read_csv(r'C:\Users\ADMIN\Desktop\ZINDUA\PYDATA\employees.csv')

In [ ]:
data.info()        # Missingness Present.

In [ ]:
data.head()

In [ ]:
data.isnull()           # At an intersection (MISSINGNESS)

In [ ]:
data.notnull()          # (COMPLETENESS)

In [ ]:
data.isnull().sum()

In [ ]:
data.notnull().sum()

In [ ]:
# Missingness within rows

data.notnull().all(axis=1)          # all ~ FIELDS (True = Complete Row)

In [ ]:
data.notnull().all(axis=0).value_counts()

In [ ]:
data.isnull().all(axis=1).value_counts()

In [ ]:
data.isnull().any(axis=1).value_counts()

In [ ]:
# Filter/Complete Dataframe

data[data.notnull().any(axis=1)]

# data[~data.isnull().any(axis=1)]

Strategies to handle missingness:
- Deleting      (.dropna)
- Imputation    (.fillna/.ffill/.bfill)

In [ ]:
# data = pd.read_csv(r'C:\Users\ADMIN\Desktop\ZINDUA\PYDATA\employees.csv')

In [ ]:
data.dropna()

In [ ]:
data.dropna(thresh=7)       # Min number of columns with missingness

In [ ]:
data.fillna(strategy = mean)

In [ ]:
data.ffill()

In [ ]:
data.bfill()

### TIME FUNCTIONALITY

In [11]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264836 entries, 0 to 264835
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   LYLTY_CARD_NBR    264836 non-null  int64
 1   LIFESTAGE         264836 non-null  object
 2   PREMIUM_CUSTOMER  264836 non-null  object
 3   DATE              264836 non-null  int64
 4   STORE_NBR         264836 non-null  int64
 5   TXN_ID            264836 non-null  int64
 6   PROD_NBR          264836 non-null  int64
 7   PROD_NAME         264836 non-null  object
 8   PROD_QTY          264836 non-null  int64
 9   TOT_SALES         264836 non-null  float64
dtypes: float64(1), int64(6), object(3)
memory usage: 20.2+ MB

In [ ]:
full_df['DATE'] = pd.to_datetime(full_df['DATE'])

In [21]:
full_df.dtypes

LYLTY_CARD_NBR               int64
LIFESTAGE                   object
PREMIUM_CUSTOMER            object
DATE                datetime64[ns]
STORE_NBR                    int64
TXN_ID                       int64
PROD_NBR                     int64
PROD_NAME                   object
PROD_QTY                     int64
TOT_SALES                  float64
dtype: object

In [16]:
full_df['DATE'].describe()

count                           264836
mean     1970-01-01 00:00:00.000043464
min      1970-01-01 00:00:00.000043282
25%      1970-01-01 00:00:00.000043373
50%      1970-01-01 00:00:00.000043464
75%      1970-01-01 00:00:00.000043555
max      1970-01-01 00:00:00.000043646
Name: DATE, dtype: object

In [46]:
df1 = full_df.copy()

In [47]:
df1['DATE'] = pd.to_numeric(df1['DATE'])

In [48]:
df1['DATE'] = pd.to_datetime(df1['DATE'],unit='D',origin='1899-12-30')

In [49]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264836 entries, 0 to 264835
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   LYLTY_CARD_NBR    264836 non-null  int64
 1   LIFESTAGE         264836 non-null  object
 2   PREMIUM_CUSTOMER  264836 non-null  object
 3   DATE              264836 non-null  datetime64[ns]
 4   STORE_NBR         264836 non-null  int64
 5   TXN_ID            264836 non-null  int64
 6   PROD_NBR          264836 non-null  int64
 7   PROD_NAME         264836 non-null  object
 8   PROD_QTY          264836 non-null  int64
 9   TOT_SALES         264836 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(5), object(3)
memory usage: 20.2+ MB

In [27]:
df1['DATE'].describe()

count                           264836
mean     2018-12-30 00:52:12.879215360
min                2018-07-01 00:00:00
25%                2018-09-30 00:00:00
50%                2018-12-30 00:00:00
75%                2019-03-31 00:00:00
max                2019-06-30 00:00:00
Name: DATE, dtype: object

In [34]:
df1.head()

,LYLTY_CARD_NBR,LIFESTAGE,PREMIUM_CUSTOMER,DATE,STORE_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,Month_Name
0,1000,YOUNG SINGLES/COUPLES,Premium,2018-10-17,1,1,5,Natural Chip Compny SeaSalt175g,2,6.0,October
1,1002,YOUNG SINGLES/COUPLES,Mainstream,2018-09-16,1,2,58,Red Rock Deli Chikn&Garlic Aioli 150g,1,2.7,September
2,1003,YOUNG FAMILIES,Budget,2019-03-07,1,3,52,Grain Waves Sour Cream&Chives 210G,1,3.6,March
3,1003,YOUNG FAMILIES,Budget,2019-03-08,1,4,106,Natural ChipCo Hony Soy Chckn175g,1,3.0,March
4,1004,OLDER SINGLES/COUPLES,Mainstream,2018-11-02,1,5,96,WW Original Stacked Chips 160g,1,1.9,November

In [ ]:
# Timestamp ~ Single date/time.
# Duration ~ Diff btw 2 timestamps.

# Datetime Module (Python)

In [50]:
import datetime as dt

Extract M, D

dt.month, dt.month_name, dt.day, dt.day_name

In [51]:
df1['Month_Name'] = df1['DATE'].dt.month_name()

TIME PERIODS

In [53]:
df1.columns

Index(['LYLTY_CARD_NBR', 'LIFESTAGE', 'PREMIUM_CUSTOMER', 'DATE', 'STORE_NBR',
       'TXN_ID', 'PROD_NBR', 'PROD_NAME', 'PROD_QTY', 'TOT_SALES',
       'Month_Name'],
      dtype='object')

In [33]:
df1['DATE'] + pd.Timedelta(5,'d')

0        2018-10-22
1        2018-09-21
2        2019-03-12
3        2019-03-13
4        2018-11-07
            ...
264831   2018-12-13
264832   2018-10-06
264833   2018-10-29
264834   2018-11-01
264835   2018-12-19
Name: DATE, Length: 264836, dtype: datetime64[ns]

In [36]:
df1['DATE'] + pd.Timedelta(1,'W')

0        2018-10-24
1        2018-09-23
2        2019-03-14
3        2019-03-15
4        2018-11-09
            ...
264831   2018-12-15
264832   2018-10-08
264833   2018-10-31
264834   2018-11-03
264835   2018-12-21
Name: DATE, Length: 264836, dtype: datetime64[ns]

In [38]:
df1['TIME'] = df1['DATE'] + pd.Timedelta(2,'Hours')

In [40]:
madaraka = pd.Timestamp(year=2018, month=12, day=12)

In [41]:
df1['DATE'] - madaraka

0        -56 days
1        -87 days
2         85 days
3         86 days
4        -40 days
           ...
264831    -4 days
264832   -72 days
264833   -49 days
264834   -46 days
264835     2 days
Name: DATE, Length: 264836, dtype: timedelta64[ns]

In [54]:
df1.columns

Index(['LYLTY_CARD_NBR', 'LIFESTAGE', 'PREMIUM_CUSTOMER', 'DATE', 'STORE_NBR',
       'TXN_ID', 'PROD_NBR', 'PROD_NAME', 'PROD_QTY', 'TOT_SALES',
       'Month_Name'],
      dtype='object')

In [55]:
df1.groupby('Month_Name')['TOT_SALES'].sum()

Month_Name
April        159845.10
August       158731.05
December     167913.40
February     150665.00
January      162642.30
July         165275.30
June         160538.60
March        166265.20
May          157367.65
November     160233.70
October      164415.70
September    160522.00
Name: TOT_SALES, dtype: float64

TIME SERIES

- DF whose index is of datetime

In [63]:
sales_df = df1[['DATE','TOT_SALES','PROD_QTY']]

In [64]:
sales_df.head()

        DATE  TOT_SALES  PROD_QTY
0 2018-10-17        6.0         2
1 2018-09-16        2.7         1
2 2019-03-07        3.6         1
3 2019-03-08        3.0         1
4 2018-11-02        1.9         1

In [65]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264836 entries, 0 to 264835
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATE       264836 non-null  datetime64[ns]
 1   TOT_SALES  264836 non-null  float64
 2   PROD_QTY   264836 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 6.1 MB

In [66]:
sales_df.set_index('DATE', inplace=True)

In [67]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 264836 entries, 2018-10-17 to 2018-12-14
Data columns (total 2 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   TOT_SALES  264836 non-null  float64
 1   PROD_QTY   264836 non-null  int64
dtypes: float64(1), int64(1)
memory usage: 6.1 MB

In [68]:
# A Time Series Now:
sales_df.head()

            TOT_SALES  PROD_QTY
DATE
2018-10-17        6.0         2
2018-09-16        2.7         1
2019-03-07        3.6         1
2019-03-08        3.0         1
2018-11-02        1.9         1

- Resampling (Grouping by index)

In [69]:
sales_df.resample('3D').sum()

            TOT_SALES  PROD_QTY
DATE
2018-07-01    16009.4      4150
2018-07-04    15995.7      4197
2018-07-07    15918.3      4221
2018-07-10    16036.0      4232
2018-07-13    16423.1      4277
...               ...       ...
2019-06-17    15403.7      4020
2019-06-20    16176.0      4219
2019-06-23    15689.5      4069
2019-06-26    15807.4      4132
2019-06-29    10921.0      2854

[122 rows x 2 columns]

In [76]:
sales_df.resample('3W').sum()

            TOT_SALES  PROD_QTY
DATE
2018-07-01    5372.20      1394
2018-07-22  112628.30     29487
2018-08-12  111402.20     29074
2018-09-02  105221.65     27534
2018-09-23  112178.70     29227
2018-10-14  112276.90     29221
2018-11-04  111452.40     29030
2018-11-25  112202.30     29383
2018-12-16  110841.60     28863
2019-01-06  114627.70     29998
2019-01-27  110324.30     28790
2019-02-17  112959.70     29476
2019-03-10  111795.90     29163
2019-03-31  113379.80     29507
2019-04-21  111533.00     29170
2019-05-12  111688.10     29214
2019-06-02  104623.55     27513
2019-06-23  112719.10     29385
2019-07-14   37187.60      9695

In [77]:
sales_df.resample('ME').sum()

            TOT_SALES  PROD_QTY
DATE
2018-07-31  165275.30     43242
2018-08-31  158731.05     41484
2018-09-30  160522.00     41792
2018-10-31  164415.70     42821
2018-11-30  160233.70     41895
2018-12-31  167913.40     43845
2019-01-31  162642.30     42501
2019-02-28  150665.00     39220
2019-03-31  166265.20     43347
2019-04-30  159845.10     41825
2019-05-31  157367.65     41300
2019-06-30  160538.60     41852

In [ ]:
# sales_df.reset_index(inplace=True)
# sales_df.resample('ME',on='OTHER COLUMN e.g.'DATE').sum()