INTRODUCTION TO PANDAS

~ Reference Material: {pandas.pydata.org}

Built on top of Numpy
Guide - pandas.pydata.org
Benefits:
1. Multidimensional operation
2.

Primary data Structures:
1. 
2.

In [1]:
import pandas as pd

Create Series Objects

1. List:

In [ ]:
num = [1,2,3,4,5]
num_series = pd.Series(num)

In [3]:
num

[1, 2, 3, 4, 5]

In [4]:
num_series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
data = pd.Series(num,index=['a','b','c','d','e'])

In [6]:
data

a    1
b    2
c    3
d    4
e    5
dtype: int64

2. Dictionary (Key - Value Pairs)

In [7]:
cities = {'Nakuru':130000, 'Voi':25000, 'Kwale':12500}

In [8]:
pop = pd.Series(cities)

In [9]:
pop

Nakuru    130000
Voi        25000
Kwale      12500
dtype: int64

Create Dataframe Objects

In [ ]:
# From a list: (Order matters)
data = [['Alice',25,'Kwale'],['Bob',30,'Turkana'],['charlie',26,'Nairobi']]

In [14]:
pd.DataFrame(data)

         0   1        2
0    Alice  25    Kwale
1      Bob  30  Turkana
2  charlie  26  Nairobi

In [ ]:
pd.DataFrame(data,columns=['Name', 'Age', 'City'])

      Name  Age     City
0    Alice   25    Kwale
1      Bob   30  Turkana
2  charlie   26  Nairobi

In [ ]:
# From a dictionary of list:
data = {'Name':['Alice','Bob','Charlie'],
        'Age':[25,30,26],
        'City':['Kwale','Turkana','Nairobi']}

In [16]:
pd.DataFrame(data)

      Name  Age     City
0    Alice   25    Kwale
1      Bob   30  Turkana
2  Charlie   26  Nairobi

In [17]:
# From a dictionary of series objects:
name_series = pd.Series(['Alice','Bob','Charlie'])
age_series = pd.Series([25,30,26])
city_series = pd.Series(['Kwale','Turkana','Nairobi'])

In [19]:
df = pd.DataFrame({'Name':name_series,'Age':age_series,'City':city_series})

In [20]:
df

      Name  Age     City
0    Alice   25    Kwale
1      Bob   30  Turkana
2  Charlie   26  Nairobi

NOTES:
> Reading data into a dataframe
> Connected to a data source (relational/non-relational)
> into a dataframe (to get the benefits of pandas)
> read data into a dataframe ~From:
eg: csv (comma seperated values)
    json
    .xlsx
    tsv (tab seperated values)

Reading Into a DataFrame Object

In [3]:
df = pd.read_csv(r'C:\Users\ADMIN\Desktop\ZINDUA\PYDATA\Week_2\mobile_sales.csv')

In [4]:
df

,TransactionID,Date,MobileModel,Brand,Price,UnitsSold,TotalRevenue,CustomerAge,CustomerGender,Location,PaymentMethod
0,79397f68-61ed-4ea8-bcb2-f918d4e6c05b,2024-01-06,direction,Green Inc,1196.95,85,28002.80,32,Female,Port Erik,Online
1,4f87d114-f522-4ead-93e3-f336402df6aa,2024-04-05,right,Thomas-Thompson,1010.34,64,2378.82,55,Female,East Linda,Credit Card
2,6750b7d6-dcc5-48c5-a76a-b6fc9d540fe1,2024-02-13,summer,Sanchez-Williams,400.80,95,31322.56,57,Male,East Angelicastad,Online
3,7da7de95-f772-4cc2-bce0-b0873f98233e,2024-04-17,keep,Greer and Sons,338.60,79,31159.75,46,Other,East Kevin,Cash
4,469044af-0d60-4d87-af66-c6603e844057,2024-06-02,option,Brown and Sons,839.79,41,11523.36,38,Male,New Lindaborough,Online
...,...,...,...,...,...,...,...,...,...,...,...
995,41f08915-addb-4966-8628-038c479c619a,2024-01-28,challenge,Brooks Ltd,1386.69,76,28865.70,39,Male,Ronaldchester,Credit Card
996,bcfa1912-5bd8-4894-900f-376fa48f022d,2024-07-13,least,"Lang, Brown and Stone",1159.26,59,50471.42,21,Other,West Jenniferport,Credit Card
997,e6839305-a177-4cda-aada-3ac1f49eeeec,2024-01-13,enjoy,"Atkinson, Moore and Nelson",544.31,59,1381.82,26,Female,Barneschester,Credit Card
998,12f7ac32-9063-4ae5-a122-385b06ba77af,2024-01-25,half,"Kim, Maxwell and Moore",331.98,84,8557.32,20,Male,Jonesborough,Online
999,d3e82026-2084-40f2-8d5d-d2a94a198af9,2024-01-17,fill,Wallace LLC,973.97,79,70739.76,44,Female,Port Luis,Credit Card

In [ ]:
# Alternatively:
df = pd.read_csv("C:/Users/ADMIN/Desktop/ZINDUA/PYDATA/Week_2/mobile_sales.csv")

7 Critical Methods:

In [5]:
# Method 1:
df.head(3)

,TransactionID,Date,MobileModel,Brand,Price,UnitsSold,TotalRevenue,CustomerAge,CustomerGender,Location,PaymentMethod
0,79397f68-61ed-4ea8-bcb2-f918d4e6c05b,2024-01-06,direction,Green Inc,1196.95,85,28002.80,32,Female,Port Erik,Online
1,4f87d114-f522-4ead-93e3-f336402df6aa,2024-04-05,right,Thomas-Thompson,1010.34,64,2378.82,55,Female,East Linda,Credit Card
2,6750b7d6-dcc5-48c5-a76a-b6fc9d540fe1,2024-02-13,summer,Sanchez-Williams,400.80,95,31322.56,57,Male,East Angelicastad,Online

In [ ]:
# Method 2:
df.tail(3)

,TransactionID,Date,MobileModel,Brand,Price,UnitsSold,TotalRevenue,CustomerAge,CustomerGender,Location,PaymentMethod
997,e6839305-a177-4cda-aada-3ac1f49eeeec,2024-01-13,enjoy,"Atkinson, Moore and Nelson",544.31,59,1381.82,26,Female,Barneschester,Credit Card
998,12f7ac32-9063-4ae5-a122-385b06ba77af,2024-01-25,half,"Kim, Maxwell and Moore",331.98,84,8557.32,20,Male,Jonesborough,Online
999,d3e82026-2084-40f2-8d5d-d2a94a198af9,2024-01-17,fill,Wallace LLC,973.97,79,70739.76,44,Female,Port Luis,Credit Card

In [ ]:
# Method 3: Print a summary of dataset. What type of data cleaning, missingness etc...
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   TransactionID   1000 non-null   object
 1   Date            1000 non-null   object
 2   MobileModel     1000 non-null   object
 3   Brand           1000 non-null   object
 4   Price           1000 non-null   float64
 5   UnitsSold       1000 non-null   int64
 6   TotalRevenue    1000 non-null   float64
 7   CustomerAge     1000 non-null   int64
 8   CustomerGender  1000 non-null   object
 9   Location        1000 non-null   object
 10  PaymentMethod   1000 non-null   object
dtypes: float64(2), int64(2), object(7)
memory usage: 86.1+ KB

In [ ]:
# Method 4:
df.columns

Index(['TransactionID', 'Date', 'MobileModel', 'Brand', 'Price', 'UnitsSold',
       'TotalRevenue', 'CustomerAge', 'CustomerGender', 'Location',
       'PaymentMethod'],
      dtype='object')

In [ ]:
# Method 5:
df.shape

(1000, 11)

In [ ]:
# Method 6:
df.describe()

             Price    UnitsSold   TotalRevenue  CustomerAge
count  1000.000000  1000.000000    1000.000000  1000.000000
mean    807.512970    50.074000   40218.445040    41.141000
std     402.489878    28.616804   32715.290358    13.528346
min     103.320000     1.000000     116.850000    18.000000
25%     458.037500    25.000000   13316.037500    29.000000
50%     823.730000    51.000000   30860.655000    41.000000
75%    1157.875000    75.000000   60770.435000    53.000000
max    1499.250000    99.000000  141411.840000    64.000000

In [ ]:
# Method 7:
df.dtypes

TransactionID      object
Date               object
MobileModel        object
Brand              object
Price             float64
UnitsSold           int64
TotalRevenue      float64
CustomerAge         int64
CustomerGender     object
Location           object
PaymentMethod      object
dtype: object

In [7]:
df.index

RangeIndex(start=0, stop=1000, step=1)

df.loc [row_index,col_index]

In [9]:
df.iloc[2,:]

TransactionID     6750b7d6-dcc5-48c5-a76a-b6fc9d540fe1
Date                                        2024-02-13
MobileModel                                     summer
Brand                                 Sanchez-Williams
Price                                            400.8
UnitsSold                                           95
TotalRevenue                                  31322.56
CustomerAge                                         57
CustomerGender                                    Male
Location                             East Angelicastad
PaymentMethod                                   Online
Name: 2, dtype: object

In [10]:
df.iloc[2,2]

'summer'

In [14]:
df.iloc[0:2,:]

,TransactionID,Date,MobileModel,Brand,Price,UnitsSold,TotalRevenue,CustomerAge,CustomerGender,Location,PaymentMethod
0,79397f68-61ed-4ea8-bcb2-f918d4e6c05b,2024-01-06,direction,Green Inc,1196.95,85,28002.80,32,Female,Port Erik,Online
1,4f87d114-f522-4ead-93e3-f336402df6aa,2024-04-05,right,Thomas-Thompson,1010.34,64,2378.82,55,Female,East Linda,Credit Card

In [15]:
df.iloc[2:5,3:8]

              Brand   Price  UnitsSold  TotalRevenue  CustomerAge
2  Sanchez-Williams  400.80         95      31322.56           57
3    Greer and Sons  338.60         79      31159.75           46
4    Brown and Sons  839.79         41      11523.36           38

In [16]:
df.iloc[2:,3:]

,Brand,Price,UnitsSold,TotalRevenue,CustomerAge,CustomerGender,Location,PaymentMethod
2,Sanchez-Williams,400.80,95,31322.56,57,Male,East Angelicastad,Online
3,Greer and Sons,338.60,79,31159.75,46,Other,East Kevin,Cash
4,Brown and Sons,839.79,41,11523.36,38,Male,New Lindaborough,Online
5,"Massey, Nicholson and Young",1498.13,70,9703.89,45,Female,Port Daryl,Debit Card
6,Coleman-Pena,975.77,63,8300.22,23,Other,Kathrynborough,Online
...,...,...,...,...,...,...,...,...
995,Brooks Ltd,1386.69,76,28865.70,39,Male,Ronaldchester,Credit Card
996,"Lang, Brown and Stone",1159.26,59,50471.42,21,Other,West Jenniferport,Credit Card
997,"Atkinson, Moore and Nelson",544.31,59,1381.82,26,Female,Barneschester,Credit Card
998,"Kim, Maxwell and Moore",331.98,84,8557.32,20,Male,Jonesborough,Online
999,Wallace LLC,973.97,79,70739.76,44,Female,Port Luis,Credit Card

df.loc [row_labels,col_labels]

In [21]:
df.columns

Index(['TransactionID', 'Date', 'MobileModel', 'Brand', 'Price', 'UnitsSold',
       'TotalRevenue', 'CustomerAge', 'CustomerGender', 'Location',
       'PaymentMethod'],
      dtype='object')

In [19]:
df.loc[0:2,'Date':'CustomerAge']

,Date,MobileModel,Brand,Price,UnitsSold,TotalRevenue,CustomerAge
0,2024-01-06,direction,Green Inc,1196.95,85,28002.80,32
1,2024-04-05,right,Thomas-Thompson,1010.34,64,2378.82,55
2,2024-02-13,summer,Sanchez-Williams,400.80,95,31322.56,57

Multi-Indexing/Hierachical Indexing

In [29]:
# Recording/Slack
# Sample sales data
data = {
    'Date': ['2022-01-01', '2022-01-01', '2022-01-02', '2022-01-02', '2022-01-03'],
    'Product': ['A', 'B', 'A', 'B', 'A'],
    'Region': ['North', 'South', 'North', 'South', 'North'],
    'Sales': [100, 150, 120, 80, 200],
    'Quantity': [2, 3, 1, 2, 4]
}

sales_df = pd.DataFrame(data)

# Convert 'Date' column to datetime type
sales_df['Date'] = pd.to_datetime(sales_df['Date'])

# Display the DataFrame
print("Sales DataFrame:")
print(sales_df)

Sales DataFrame:
        Date Product Region  Sales  Quantity
0 2022-01-01       A  North    100         2
1 2022-01-01       B  South    150         3
2 2022-01-02       A  North    120         1
3 2022-01-02       B  South     80         2
4 2022-01-03       A  North    200         4

In [23]:
sales_df.index

RangeIndex(start=0, stop=5, step=1)

In [25]:
sales_df.set_index(['Date'],inplace=True)

In [26]:
sales_df

           Product Region  Sales  Quantity
Date
2022-01-01       A  North    100         2
2022-01-01       B  South    150         3
2022-01-02       A  North    120         1
2022-01-02       B  South     80         2
2022-01-03       A  North    200         4

In [27]:
sales_df.index

DatetimeIndex(['2022-01-01', '2022-01-01', '2022-01-02', '2022-01-02',
               '2022-01-03'],
              dtype='datetime64[ns]', name='Date', freq=None)

In [28]:
sales_df.columns

Index(['Product', 'Region', 'Sales', 'Quantity'], dtype='object')

In [30]:
sales_df

        Date Product Region  Sales  Quantity
0 2022-01-01       A  North    100         2
1 2022-01-01       B  South    150         3
2 2022-01-02       A  North    120         1
3 2022-01-02       B  South     80         2
4 2022-01-03       A  North    200         4

In [31]:
mindex_df = sales_df.set_index(['Date','Region'])

In [32]:
mindex_df

                  Product  Sales  Quantity
Date       Region
2022-01-01 North        A    100         2
           South        B    150         3
2022-01-02 North        A    120         1
           South        B     80         2
2022-01-03 North        A    200         4

In [36]:
mindex_df[['Product']]

                  Product
Date       Region
2022-01-01 North        A
           South        B
2022-01-02 North        A
           South        B
2022-01-03 North        A

In [35]:
mindex_df[['Product','Quantity']]

                  Product  Quantity
Date       Region
2022-01-01 North        A         2
           South        B         3
2022-01-02 North        A         1
           South        B         2
2022-01-03 North        A         4

In [37]:
mindex_df.loc[:,'Product':'Quantity']

                  Product  Sales  Quantity
Date       Region
2022-01-01 North        A    100         2
           South        B    150         3
2022-01-02 North        A    120         1
           South        B     80         2
2022-01-03 North        A    200         4

In [38]:
mindex_df.loc['2022-01-02','Product':'Quantity']

       Product  Sales  Quantity
Region
North        A    120         1
South        B     80         2

In [39]:
mindex_df.loc['2022-01-02',:]

       Product  Sales  Quantity
Region
North        A    120         1
South        B     80         2

In [40]:
mindex_df.loc[(slice(None),'South'),:]

                  Product  Sales  Quantity
Date       Region
2022-01-01 South        B    150         3
2022-01-02 South        B     80         2

In [48]:
three_level_df = sales_df.set_index(['Date','Product','Region'])
three_level_df

                           Sales  Quantity
Date       Product Region
2022-01-01 A       North     100         2
           B       South     150         3
2022-01-02 A       North     120         1
           B       South      80         2
2022-01-03 A       North     200         4

In [49]:
three_level_df.loc[(slice(None),slice(None),slice(None))]

                           Sales  Quantity
Date       Product Region
2022-01-01 A       North     100         2
           B       South     150         3
2022-01-02 A       North     120         1
           B       South      80         2
2022-01-03 A       North     200         4

In [50]:
three_level_df.loc[(slice(None),'B',slice(None))]

                   Sales  Quantity
Date       Region
2022-01-01 South     150         3
2022-01-02 South      80         2

Unstack