GroupBy:
(pip install openpyxl)

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv(r'C:\Users\ADMIN\Desktop\ZINDUA\PYDATA\QVI_purchase_behaviour.csv')

In [5]:
df = pd.read_excel(r'C:\Users\ADMIN\Desktop\ZINDUA\PYDATA\QVI_transaction_data.xlsx')

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72637 entries, 0 to 72636
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   LYLTY_CARD_NBR    72637 non-null  int64
 1   LIFESTAGE         72637 non-null  object
 2   PREMIUM_CUSTOMER  72637 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.7+ MB

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264836 entries, 0 to 264835
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DATE            264836 non-null  int64
 1   STORE_NBR       264836 non-null  int64
 2   LYLTY_CARD_NBR  264836 non-null  int64
 3   TXN_ID          264836 non-null  int64
 4   PROD_NBR        264836 non-null  int64
 5   PROD_NAME       264836 non-null  object
 6   PROD_QTY        264836 non-null  int64
 7   TOT_SALES       264836 non-null  float64
dtypes: float64(1), int64(6), object(1)
memory usage: 16.2+ MB

In [6]:
full_df = data.merge(df,how='left',on='LYLTY_CARD_NBR')

In [8]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264836 entries, 0 to 264835
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   LYLTY_CARD_NBR    264836 non-null  int64
 1   LIFESTAGE         264836 non-null  object
 2   PREMIUM_CUSTOMER  264836 non-null  object
 3   DATE              264836 non-null  int64
 4   STORE_NBR         264836 non-null  int64
 5   TXN_ID            264836 non-null  int64
 6   PROD_NBR          264836 non-null  int64
 7   PROD_NAME         264836 non-null  object
 8   PROD_QTY          264836 non-null  int64
 9   TOT_SALES         264836 non-null  float64
dtypes: float64(1), int64(6), object(3)
memory usage: 20.2+ MB

What can we ask from this dat?

- Univariate, Bivariate & Multivariate Analysis (Global View - Summary Stats)
1. Univariate:
- How big is our customer base
- How many unique products
- When does my dataset range from?
- How many transaction
- Total quantity sold
- Distribution; How many customers; lifestage, premium customer
- Distribution of sales (); Median sales, outliers
- Distribution of premium customer by lifestage
- Quantity by lifestage & premium customer
- Total sales by lifestage & premium customer

In [9]:
full_df.columns

Index(['LYLTY_CARD_NBR', 'LIFESTAGE', 'PREMIUM_CUSTOMER', 'DATE', 'STORE_NBR',
       'TXN_ID', 'PROD_NBR', 'PROD_NAME', 'PROD_QTY', 'TOT_SALES'],
      dtype='object')

In [10]:
full_df['LIFESTAGE'].nunique()

7

In [14]:
full_df.groupby('LIFESTAGE')[['TOT_SALES']].sum().sort_values(by='TOT_SALES',ascending=False)

                        TOT_SALES
LIFESTAGE
OLDER SINGLES/COUPLES   402426.75
RETIREES                366470.90
OLDER FAMILIES          353767.20
YOUNG FAMILIES          316160.10
YOUNG SINGLES/COUPLES   260405.30
MIDAGE SINGLES/COUPLES  184751.30
NEW FAMILIES             50433.45

In [15]:
full_df.groupby(['LIFESTAGE','PREMIUM_CUSTOMER'])[['TOT_SALES']].mean()

                                         TOT_SALES
LIFESTAGE              PREMIUM_CUSTOMER
MIDAGE SINGLES/COUPLES Budget             7.074661
                       Mainstream         7.647284
                       Premium            7.112056
NEW FAMILIES           Budget             7.297321
                       Mainstream         7.317806
                       Premium            7.231655
OLDER FAMILIES         Budget             7.269570
                       Mainstream         7.262395
                       Premium            7.322945
OLDER SINGLES/COUPLES  Budget             7.430315
                       Mainstream         7.282116
                       Premium            7.449766
RETIREES               Budget             7.443445
                       Mainstream         7.252262
                       Premium            7.456174
YOUNG FAMILIES         Budget             7.287201
                       Mainstream         7.189025
                       Premium            7.266756
YOUNG SINGLES/COUPLES  Budget             6.615624
                       Mainstream         7.558339
                       Premium            6.629852

In [16]:
full_df.groupby(['LIFESTAGE','PREMIUM_CUSTOMER'])[['TOT_SALES','PROD_QTY']].mean()

                                         TOT_SALES  PROD_QTY
LIFESTAGE              PREMIUM_CUSTOMER
MIDAGE SINGLES/COUPLES Budget             7.074661  1.891633
                       Mainstream         7.647284  1.911656
                       Premium            7.112056  1.889727
NEW FAMILIES           Budget             7.297321  1.853910
                       Mainstream         7.317806  1.857634
                       Premium            7.231655  1.860919
OLDER FAMILIES         Budget             7.269570  1.945812
                       Mainstream         7.262395  1.948610
                       Premium            7.322945  1.980969
OLDER SINGLES/COUPLES  Budget             7.430315  1.913403
                       Mainstream         7.282116  1.910525
                       Premium            7.449766  1.914273
RETIREES               Budget             7.443445  1.892244
                       Mainstream         7.252262  1.887543
                       Premium            7.456174  1.900122
YOUNG FAMILIES         Budget             7.287201  1.940749
                       Mainstream         7.189025  1.940342
                       Premium            7.266756  1.937732
YOUNG SINGLES/COUPLES  Budget             6.615624  1.803830
                       Mainstream         7.558339  1.852498
                       Premium            6.629852  1.804012

In [17]:
full_df.groupby(['LIFESTAGE']).agg({'TOT_SALES:'sum',
                                    'PROD_QTY':mean'})

SyntaxError: unterminated string literal (detected at line 1) (1547519370.py, line 1)

In [ ]:
# Check recording for final part.

Pivot Table:

In [ ]:
pd.pivot_table(full_df,values=['TOT_SALES', 'PROD_QTY'], index='LIFESTAGE', columns='PREMIUM_CUSTOMER',agg({mean}))

MISSINGNESS

In [20]:
data = pd.read_csv(r'C:\Users\ADMIN\Desktop\ZINDUA\PYDATA\employees.csv', encoding='utf-16')

UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 76-77: illegal UTF-16 surrogate